server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://172.17.01:3306/jxmall
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl